signing_registration_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import home, register,user_login,user_logout
app_name='signing_registration_app'
urlpatterns = [
    path('', home, name='home'),
    path('register/',register,name='register'),
    path('login/',user_login,name='login'),
    path('logout/',user_logout,name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

signing_registration_project/urls.py
from django.contrib import admin
from django.urls import path,include
import signing_registration_app.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include(signing_registration_app.urls))
]

signing_registration_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
#the class BaseUserManager is used to create a custom user model
#we are inheriting from the BasUserManager class to use the built-in user
# already provided by django to create a custom user model
# we will override the create_user method to create a custom user model
# we will also override the create_superuser method to create a superuser
class CustomUserManager(BaseUserManager):
    #the custom user model will have an email field and a password field
    # the email field will be used to login instead of the username field
    # the username field will be removed
    # the email field will be the unique identifier for the user
    # (**extra_fields) will be used to pass in any extra fields that
    # we want to add to the user model
    
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("Email is required")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        #the set_password method is used to hash the password
        #the password is hashed for security reasons
        #the password is not stored in plain text
        #the set_password method is a built-in method that
        # use the algorithm PBKDF2 to encrypt the password
        user.set_password(password)
        #using=self._db is used to save the user to the database
        
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    # def create_superuser(self, email, password, **extra_fields):
    #     #the extra_fields parameter is used to pass in any extra fields
    #     # that we want to add to the user model
    #     # we will not use the extra_fields parameter in this method
    #     # we will use the extra_fields parameter in the create_user method
    #     # the extra_fields parameter is used to pass in any extra fields
    #     # that we want to add to the user model
    #     # we will not use the extra_fields parameter in this method
    #     # we will use the extra_fields parameter in the create_user method
    #     # the extra_fields parameter is used to pass in any extra fields
    #     # that we want to add to the user model
    #     # we will not use the extra_fields parameter in this method
    #     # we will use the extra_fields parameter in the create_user method
    #     # the extra_fields parameter is used to pass in any extra fields
    #     # that we want to add to the user model
    #     # we will not use the extra_fields parameter in this method
    #     # we will use the extra_fields parameter in the create_user method
    #     # the extra_fields parameter is used to pass in any extra fields
    #     # that we want to add to the user model
    #     # we will not use the extra_fields parameter in this method
    #     # we will use the extra_fields parameter in the create_user method
    #     # the extra_fields parameter is used to pass in any extra fields
    #     # that we want to add
    #     # to the user model
    #     #the is_staff field is used to determine if the user is a staff member
    #     extra_fields.setdefault('is_staff', True)
    #     #the is_superuser field is used to determine if the user is a superuser
    #     extra_fields.setdefault('is_superuser', True)
    #     #the is_active field is used to determine if the user is active
    #     #users are active if they have verified their email address
    #     extra_fields.setdefault('is_active', True)
    #     return self.create_user(email, password, **extra_fields)


    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    photo = models.ImageField(upload_to='photos', blank=True)
    birthday = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()
    class Meta:
        db_table = 'customer_user'
        verbose_name = 'user'
        verbose_name_plural = 'users'
        ordering = ['first_name', 'last_name']
    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

# class User(AbstractBaseUser, PermissionsMixin):
#     #the username field will be removed
#     #the email field will be used to login instead of the username field
#     #the email field will be the unique identifier for the user
#     email = models.EmailField(unique=True)
#     #the first_name field is used to store the user's first name
#     first_name = models.CharField(max_length=50)
#     #the last_name field is used to store the user's last name
#     last_name = models.CharField(max_length=50)
#     #the is_staff field is used to determine if the user is a staff member
#     is_staff = models.BooleanField(default=False)
#     #the is_superuser field is used to determine if the user is a superuser
#     is_superuser = models.BooleanField(default=False)
#     #the is_active field is used to determine if the user is active
#     #users are active if they have verified their email address
#     is_active = models.BooleanField(default=True)
#     #the date_joined field is used to determine when the user joined
#     date_joined = models.DateTimeField(auto_now_add=True)
#     #the last_login field is used to determine when the user last logged in
#     last_login = models.DateTimeField(auto_now=True)
#     #the USERNAME_FIELD is used to determine which field will be used to login
#     #the email field will be used to login instead of the username field
#     USERNAME_FIELD = 'email'
#     #the REQUIRED_FIELDS is used to determine which fields are required
#     #when a user is created
#     REQUIRED_FIELDS = ['first_name', 'last_name']
#     #the objects field is used to create a CustomUserManager object
#     objects = CustomUserManager()

#     def __str__(self):
#         return self.email
    

signing_registration_app/forms.py
from django.utils.translation import gettext_lazy as _
from django.forms import DateInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser
from django import forms

class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'photo', 'birthday')
        widgets = {
            'birthday': DateInput(attrs={'type': 'date'})
        }

class CustomAuthenticationForm(AuthenticationForm):
   class Meta:
        model = CustomUser
        fields = ('email', 'password')
        widgets = {
            'email': forms.EmailInput(attrs={'autofocus': True}),
        }
        labels = {
            'email': _('Email'),
        }
        error_messages = {
            'email': {
                'required': _('Please enter your email'),
                'invalid': _('Please enter a valid email address'),
            },
            'password': {
                'required': _('Please enter your password'),
            },
        }

signing_registration_app/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import RegistrationForm, CustomAuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages

#the render method is used to render a html page
#the redirect method is used to redirect to a specific url
#render parameters are request and the html page to be rendered
# rendering parameters could contain a dictionary of variables to be used in the html page
#redirect parameters are the url to be redirected to
def home(request):
    return render(request, 'accounts/base.html')

def user_login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        print('form = ',form)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print(email, password)
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('signing_registration_app:home')
            else:
                messages.error(request, 'Invalid email or password. Please try again.')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('signing_registration_app:home')
    else:
        form = RegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

@login_required
def user_logout(request):
    logout(request)
    return redirect('signing_registration_app:login')

signing_registration_app/templates/accounts/base.html
{% comment %}
{% load static%} tag is used to load static files like css, js, images etc.
{% static 'css/style.css' %} is used to load static files from static folder.
{% url 'signing_registration_app:logout' %} is used to load url from urls.py file.
{% if user.is_authenticated %} is used to check if user is logged in or not.
{% else %} is used to check if user is not logged in.
{% block title %}My Site{% endblock %} is used to set title of the page.
{% block content %}{% endblock %} is used to set content of the page.
{{ user.get_full_name }} is used to get full name of the user.
{% endcomment %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <p>Welcome, {{ user.get_full_name }} (<a href="{% url 'signing_registration_app:logout' %}">Logout</a>)</p>
      {% else %}
      <p><a href="{% url 'signing_registration_app:login' %}">Login</a> | <a href="{% url 'signing_registration_app:register' %}">Register</a></p>
      {% endif %}
    </header>
    {% comment %} <main> tag is used to set content of the page.
    {% block content %}{% endblock %} is used to set content of the page.
    
         {% endcomment %}
    <main>
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

signing_registration_app/templates/accounts/home.html
{% comment %}
the extend tag is used to extend an other template
 {% endcomment %}
{% extends 'base.html' %}
{% comment %}
the block tag is used to define a block template
csrf_token tag is used to generate a CSRF token
The CSRF token is used to protect against Cross Site Request Forgeries
This vulnerability is about tricking a user into submitting a request they did not intend.
In simply words, the CSRF token is used to prevent a malicious website from sending requests to a website where the user is logged in.
{% endcomment %}
{% block content %}
  <h1>Welcome, {{ user.email }}!</h1>
  <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">Logout</button>
  </form>
{% endblock %}

signing_registration_app/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {% comment %}
    form.as_p is a shortcut for rendering each field wrapped in a paragraph tag
    more simply, it's used to render the form in a more readable way
    the p is for pretty printing
     {% endcomment %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

signing_registration_app/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block content %}
  <h2>Register</h2>
  {% comment %}
enctype="multipart/form-data is required for file uploads
it is used to encode the form data as a multipart/form-data request
  {% endcomment %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}